In [1]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

In [2]:
digits = load_digits()
data = digits.data
target = digits.target
print(data.shape,target.shape)
x_train,x_test,y_train,y_test = train_test_split(data,target,test_size=0.1)

(1797, 64) (1797,)


In [5]:
data[1]

array([ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
        9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
       15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
        0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
       16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.])

In [46]:
clf = DecisionTreeClassifier(max_depth=15)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print("单棵决策树分类结果如下：")
print("混淆矩阵:")
print(confusion_matrix(y_pred,y_test))
print("训练集分数：",clf.score(x_train,y_train))
print("验证集分数：",clf.score(x_test,y_test))

单棵决策树分类结果如下：
混淆矩阵:
[[23  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  1  0  0  2]
 [ 0  3 16  0  0  0  0  1  0  0]
 [ 0  1  0 10  0  1  0  0  2  1]
 [ 0  0  0  0 14  1  0  1  0  0]
 [ 0  0  0  1  0 10  0  0  0  1]
 [ 1  0  0  0  1  0 18  0  0  0]
 [ 0  0  0  1  0  0  0 16  0  2]
 [ 1  1  0  3  0  0  0  0 14  0]
 [ 0  0  0  2  0  2  0  1  1 16]]
训练集分数： 0.9993815708101422
验证集分数： 0.8222222222222222


In [64]:
clf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=10),
                         n_estimators=40,
                         learning_rate=0.5,
                         algorithm='SAMME'
                         )
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print("Adaboost分类器（多棵决策树）分类结果如下：")
print("混淆矩阵:")
print(confusion_matrix(y_pred,y_test))
print("训练集分数：",clf.score(x_train,y_train))
print("验证集分数：",clf.score(x_test,y_test))


Adaboost分类器（多棵决策树）分类结果如下：
混淆矩阵:
[[25  0  0  0  0  0  0  0  0  0]
 [ 0 16  0  0  0  0  0  0  0  0]
 [ 0  0 16  0  0  0  0  0  0  0]
 [ 0  0  0 17  0  0  0  0  0  0]
 [ 0  0  0  0 15  1  0  0  0  0]
 [ 0  0  0  0  0 12  0  0  0  1]
 [ 0  0  0  0  0  0 19  0  0  0]
 [ 0  0  0  0  0  0  0 19  0  0]
 [ 0  0  0  0  0  0  0  0 15  0]
 [ 0  0  0  0  0  1  0  0  2 21]]
训练集分数： 1.0
验证集分数： 0.9722222222222222


In [3]:
import math
import numpy as np

a = math.log(2)
b = np.log(2)

In [4]:
a, b

(0.6931471805599453, 0.6931471805599453)

In [32]:
a = np.random.randint(1, 10, 10)

In [35]:
a = [1, 1, 1, 2, 2, 3, 4]

In [36]:
a = np.array(a)

In [40]:
a[a==2]

array([2, 2])

In [30]:
def f(y):
      # 计算节点，出现最多
        most_common = None
        max_count = 0
        for label in np.unique(y):
            # Count number of occurences of samples with label
            count = len(y[y == label])
            if count > max_count:
                most_common = label
                max_count = count
        # print("most_common :",most_common)
        return most_common

In [48]:
a = np.random.randint(1, 10, (5, 10))
b = np.random.randint(0, 1, (5, 1))
a1 = np.random.randint(1, 10, (1, 10))

In [50]:
c = np.concatenate((a, b), axis=1)
c

array([[7, 2, 2, 8, 2, 9, 9, 4, 6, 2, 0],
       [4, 7, 1, 4, 6, 2, 1, 3, 2, 3, 0],
       [2, 6, 4, 1, 9, 9, 8, 5, 4, 6, 0],
       [6, 5, 5, 9, 7, 8, 6, 8, 2, 2, 0],
       [6, 6, 3, 2, 7, 4, 2, 7, 3, 2, 0]])

In [64]:
d = np.concatenate((a, a1), axis=0)
d

array([[7, 2, 2, 8, 2, 9, 9, 4, 6, 2],
       [4, 7, 1, 4, 6, 2, 1, 3, 2, 3],
       [2, 6, 4, 1, 9, 9, 8, 5, 4, 6],
       [6, 5, 5, 9, 7, 8, 6, 8, 2, 2],
       [6, 6, 3, 2, 7, 4, 2, 7, 3, 2],
       [6, 6, 8, 1, 2, 6, 7, 3, 3, 5]])

In [65]:
d1 = d[:, 1]
d2 = np.expand_dims(d1, axis=1)
d2

array([[2],
       [7],
       [6],
       [5],
       [6],
       [6]])

In [67]:
a = [[2, 2]]
b = zip(*a)