In [1]:
import numpy as np

In [52]:
a = np.random.randint(1, 10, (3,3))
a

array([[6, 3, 4],
       [7, 5, 2],
       [5, 6, 2]])

In [53]:
a

array([[6, 3, 4],
       [7, 5, 2],
       [5, 6, 2]])

In [54]:
np.sqrt(a)

array([[2.44948974, 1.73205081, 2.        ],
       [2.64575131, 2.23606798, 1.41421356],
       [2.23606798, 2.44948974, 1.41421356]])

In [55]:
np.multiply(a, np.ones_like(a))

array([[6, 3, 4],
       [7, 5, 2],
       [5, 6, 2]])

In [57]:
a.dot(np.ones_like(a))

array([[13, 13, 13],
       [14, 14, 14],
       [13, 13, 13]])

In [51]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = a * b
c

array([1, 4, 9])

In [ ]:
from sklearn import RegressionTree
print ("-- Classification Tree --")

data = datasets.load_boston()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

clf = RegressionTree()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
mse = mean_squared_error(y_pred, y_test)
#accuracy = accuracy_score(y_test, y_pred)

#print ("Accuracy:", accuracy)
print ("loss:", mse)
#clf.print_tree()

In [58]:
y = np.random.randint(1, 10, 10)
y

array([6, 7, 6, 1, 3, 8, 8, 3, 6, 4])

In [59]:
idx = [2, 3, 1, 8]
y_label = y[idx]
y_label

array([6, 1, 7, 6])

In [63]:
x1 = np.random.randint(1, 10, 10)
x1 = np.expand_dims(x1, axis=1)
x2 = np.random.randint(1, 10, 10)
x2 = np.expand_dims(x2, axis=1)
distance1 = np.sqrt(np.sum(np.power(x1-x2, 2)))
distance1

11.789826122551595

In [64]:
distance2 = 0
for i in range(len(x1)):
    distance2 += np.power(x1[i] - x2[i], 2)
distance2 = np.sqrt(distance2)
distance2

array([11.78982612])

In [68]:
s = 'sadas'
s = list(s)
s.remove('s')
s

['a', 'd', 'a', 's']

In [70]:
from itertools import permutations as per
res = per(s)
list(res)

[('a', 'd', 'a', 's'),
 ('a', 'd', 's', 'a'),
 ('a', 'a', 'd', 's'),
 ('a', 'a', 's', 'd'),
 ('a', 's', 'd', 'a'),
 ('a', 's', 'a', 'd'),
 ('d', 'a', 'a', 's'),
 ('d', 'a', 's', 'a'),
 ('d', 'a', 'a', 's'),
 ('d', 'a', 's', 'a'),
 ('d', 's', 'a', 'a'),
 ('d', 's', 'a', 'a'),
 ('a', 'a', 'd', 's'),
 ('a', 'a', 's', 'd'),
 ('a', 'd', 'a', 's'),
 ('a', 'd', 's', 'a'),
 ('a', 's', 'a', 'd'),
 ('a', 's', 'd', 'a'),
 ('s', 'a', 'd', 'a'),
 ('s', 'a', 'a', 'd'),
 ('s', 'd', 'a', 'a'),
 ('s', 'd', 'a', 'a'),
 ('s', 'a', 'a', 'd'),
 ('s', 'a', 'd', 'a')]

In [74]:
a = np.random.randint(1, 10 ,10)
b = np.linalg.norm(a, 2, axis=-1)
b

19.8997487421324

In [76]:
a.shape

(10,)

In [83]:
a = np.random.randint(1, 10, (2, 2, 2))
a.shape

(2, 2, 2)

In [88]:
b = np.expand_dims(a, axis=-1)
b.shape

(2, 2, 2, 1)

In [101]:
a = np.random.randint(1, 10, 10)
a == 2

array([False,  True, False, False, False, False,  True, False,  True,
        True])

In [102]:
np.mean(a==2)

0.4

In [104]:
np.exp(1)

2.718281828459045

In [111]:
d = {}
d['s'] = {}
d['s'][1] = 1
d

{'s': {1: 1}}

In [119]:
a = np.random.randint(1, 10, 10)
b = np.random.randint(1, 10, 10)
for (i, x), y in zip(enumerate(a), b):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [120]:
from sklearn import datasets
data = datasets.load_iris()

In [122]:
    X = data.data
    y = data.target

In [123]:
a = [isinstance(any(x), float) for x in X.T]

In [130]:
isinstance(any(X.T[1]), float)

False

In [138]:
isinstance(X.T[0], float)

TypeError: 'bool' object is not iterable

In [149]:
d = np.random.randint(1, 10, 10)


bool

In [152]:
[isinstance(x[0], float) for x in X.T]

[True, True, True, True]

In [158]:
class Solution:
    def floodFill(self, image, sr, sc, newColor):
        r, c = len(image), len(image[0])
        res = [[sr, sc]]
        visited = [[1 for _ in range(c)] for _ in range(r)]
        visited[sr][sc] = 1
        points = [[sr, sc]]
        while points:
            temp = []
            for x, y in points:
                for dx, dy in [[1, 0], [-1, 0], [0, 1], [0, -1]]:
                    i = x + dx
                    j = y + dy
                    if 0 <= i < r and 0 <= j < c and visited[i][j] and image[x][y] ==  image[i][j]:
                        visited[i][j] = 0
                        temp.append([i, j])
                        res.append([i, j])
            points = temp
        for i, j in res:
            image[i][j] = newColor
        return image

In [159]:
a = Solution()

In [160]:
image =[[0,0,0],[0,0,0]]
sr = 0
sc = 0
newColor = 2

In [161]:
a.floodFill(image, sr, sc, newColor)

[[2, 2, 2], [2, 2, 2]]

In [8]:
import numpy as np
a = [[1, 2], [3, 4]]
a = np.array(a)
a[:, 1]

array([2, 4])

In [10]:
n = 3
helper = [['.' for _ in range(n)] for _ in range(n)]
helper

[['.', '.', '.'], ['.', '.', '.'], ['.', '.', '.']]

In [17]:
helper = [''.join(x) for x in helper]
helper

['...', '...', '...']

In [43]:
a = np.array([1, 1, 1, 2, 3, 2])
b = (a == 1)
a[b]

array([1, 1, 1])

In [44]:
b

array([ True,  True,  True, False, False, False])

In [62]:
error = 0.2
0.5 * np.log((1.0 - error) / (error + 1e-5))

0.6931221811849244

In [63]:
n_samples = 10
y_pred = np.zeros((n_samples, 1))

In [64]:
y_pred

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [65]:
n_samples = 10
w = np.full(n_samples, (1 / n_samples))

In [86]:
import math
def calculate_entropy(y):
    """ Calculate the entropy of label array y """
    log2 = lambda x: math.log(x) / math.log(2)
    unique_labels = np.unique(y)
    entropy = 0
    for label in unique_labels:
        count = len(y[y == label])
        p = count / len(y)
        entropy -= p * log2(p)
    return entropy

In [91]:
def _calculate_information_gain(y, y1, y2):
        # Calculate information gain
        p = len(y1) / len(y)
        entropy = calculate_entropy(y)
        info_gain = entropy - p * \
            calculate_entropy(y1) - (1 - p) * \
            calculate_entropy(y2)

        return info_gain

In [92]:
from sklearn import datasets
data = datasets.load_iris()
X = data.data
y = data.target
y_pred = np.full(y.shape, np.mean(y, axis=0))
a = np.array([y_pred, y_pred, y_pred])
y0, y1, y2 = a[:20], a[20:40], a[40:]

In [93]:
b = _calculate_information_gain(y0, y1, y2)

In [95]:
b

-1084.322803574382

In [96]:
def calEntropy(Y):
    entropy = 0.0
    log2 = lambda x: np.log(x)/np.log(2)
    unique_labels = np.unique(Y)
    n = len(Y)

    for label in unique_labels:
        p = len(Y[Y == label])/n
        entropy -= p*log2(p)
    return entropy

# 计算信息增益
def calGain(y, y0, y1):
    EntD = calEntropy(y)
    p = len(y0) / len(y)
    Gain = EntD - p * calEntropy(y0) - (1 - p) * calEntropy(y1)
    return Gain

In [97]:
bb = calGain(y0, y1, y2)

In [98]:
bb

-1084.322803574382

In [14]:
A = [1,2,3,0,0,0]
B = [2,5]
A[3: 3 + 2] = B
A

[1, 2, 3, 2, 5, 0]

In [15]:
A = A + [B]

In [17]:
A[-1][-1]

5

In [25]:
class Solution:
    def pileBox(self, box):
        self.res = 0
        def bfs(boxes, path, ans):
            self.res = max(self.res, ans)
            for i,b in enumerate(boxes):
                if not path or (path[-1][0] > b[0] and path[-1][1] > b[1] and path[-1][2] > b[2]):
                    print(path)
                    temp = boxes[:i] + boxes[i + 1:]
                    bfs(temp, path + [b], ans + b[-1])
        bfs(box, [], 0)
        return self.res

In [26]:
s = Solution()
box = [[1, 1, 1], [2, 3, 4], [2, 6, 7], [3, 4, 5]]
s.pileBox(box)

[]
[]
[[2, 3, 4]]
[]
[[2, 6, 7]]
[]
[[3, 4, 5]]
[[3, 4, 5]]
[[3, 4, 5], [2, 3, 4]]


10

In [27]:
sorted(box)

[[1, 1, 1], [2, 3, 4], [2, 6, 7], [3, 4, 5]]

In [32]:
eval(str(True)+'&'+str(False))

False

In [37]:
(1 == True) + True

2

In [40]:
eval('1') + True

2

In [63]:
class Solution:
    def countEval(self, s: str, result: int) -> int:
        self.ops = {
            '&': {
                True: [(True, True)],
                False: [(True, False), (False, True), (False, False)]
            },
            '|': {
                True: [(True, False), (False, True), (True, True)],
                False: [(False, False)]
            },
            '^': {
                True: [(True, False), (False, True)],
                False: [(True, True), (False, False)]
            }
        }

        def divide(expression, result, dic):
            if len(expression) == 1:
                return int(eval(expression)==result)
            
            if (expression, result) in dic:
                return dic[(expression, result)]
            
            total = 0
            for i, express in enumerate(expression):
                if express in '&|^':
                    for left, right in self.ops[express][result]:
                        total += divide(expression[:i], left, dic) * divide(expression[i+1:], right, dic)
            dic[(expression, result)] = total

            return total
        
        res = divide(s, result, {})
        return res




In [64]:
p = Solution()
s = "0&0&0&1^1|0"
result = 1
p.countEval(s, result)

10

In [71]:
import numpy as np
def loss(y, p):
    # Avoid division by zero
    p = np.clip(p, 1e-15, 1 - 1e-15)
    return - y * np.log(p) - (1 - y) * np.log(1 - p)

In [73]:
y = np.array([1, 0, 1])
p = np.array([0.1, 0.1, 0.9])
loss(y, p)

array([2.30258509, 0.10536052, 0.10536052])

In [74]:
loss(p, y)

array([31.08561839,  3.45387764,  3.4539576 ])

In [76]:
y_pred = np.random.randint(1, 10, (10, 10))
y_pred = np.exp(y_pred) / np.sum(np.exp(y_pred), axis=1, keepdims=True)
np.argmax(y_pred, axis=1)

array([5, 0, 7, 3, 2, 1, 9, 0, 4, 4], dtype=int64)

In [78]:
a = np.zeros_like(y_pred)
b = np.zeros(y_pred.shape)

In [82]:
sorted('asfds')

['a', 'd', 'f', 's', 's']

In [89]:
5 > 3 < 2

True

In [111]:
ans = [1, 3, 4, 5, 7, 10, 14]
target = 5
def find_target(target, ans):
    l, r = 0, len(ans) - 1
    flag = 0
    while l <= r:
        m = l + (r - l >> 1)
        if ans[m] == target:
            flag = 1
            while ans[m] == target:
                m -= 1
            break
        elif ans[m] < target:
            l = m + 1
        else:
            r = m - 1
    return m + 1

In [121]:
def find_i(arr):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = left + (right - left >> 1)
        print('left:', left, 'mid:', mid, 'right:', right)
        if (mid == 0 and arr[mid] < arr[mid+1]) or mid == len(arr) - 1 or (arr[mid - 1] > arr[mid] <= arr[mid + 1]):
            break
        elif arr[mid] <= arr[left]:
            right = mid
        else:
            left = mid + 1
    return mid

In [94]:
arr = [15, 16, 19, 20, 25, 1, 3, 4, 5, 7, 10, 14]

In [100]:
arr1 = [1,1,1,1,1,2,1,1,1]

In [112]:
find_target(2, arr1[:6])

5